# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: false
      settings:
        MinVersion: '10.0.22621'
        
  resources:
  
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: false
      settings:
        Ensure: Present
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Professional
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudio.2022.Professional
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscodePackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscodeInsidersPackage
      directives:
        description: Install Visual Studio Code Insiders
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode.Insiders
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dotnetCore9
      directives:
        description: Install .NET Core 9 SDK
        allowPrerelease: false
      settings:
        id: Microsoft.DotNet.SDK.9
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: gitPackage
      directives:
        description: Install Git
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: githubDesktopPackage
      directives:
        description: Install GitHub Desktop
      settings:
        id: GitHub.GitHubDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nvmPackage
      directives:
        description: Install NVM for Windows
      settings:
        id: CoreyButler.NVMforWindows
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: redisInsightPackage
      directives:
        description: Install RedisInsight
      settings:
        id: XP8K1GHCB0F1R2
        source: msstore
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: sqlServerManagementStudioPackage
      directives:
        description: Install Microsoft SQL Server Management Studio (SSMS)
      settings:
        id: Microsoft.SQLServerManagementStudio
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dockerDesktopPackage
      directives:
        description: Install Docker Desktop
        allowPrerelease: false
      settings:
        id: Docker.DockerDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: notionPackage
      directives:
        description: Install Notion
        allowPrerelease: false
      settings:
        id: Notion.Notion
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: shareXPackage
      directives:
        description: Install ShareX
        allowPrerelease: false
      settings:
        id: ShareX.ShareX
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nugetPackage
      directives:
        description: Install NuGet
        allowPrerelease: false
      settings:
        id: Microsoft.NuGet
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: treeSizePackage
      directives:
        description: Install TreeSize
        allowPrerelease: false
      settings:
        id: JAMSoftware.TreeSize.Free
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powerShellPackage
      directives:
        description: Install PowerShell
        allowPrerelease: false
      settings:
        id: Microsoft.PowerShell
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohMyPoshPackage
      directives:
        description: Install OhMyPosh
        allowPrerelease: false
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: 7zipPackage
      directives:
        description: Install 7zip
        allowPrerelease: false
      settings:
        id: 7zip.7zip
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: gIMPPackage
      directives:
        description: Install GIMP
        allowPrerelease: false
      settings:
        id: GIMP.GIMP
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: sysinternalsPackage
      directives:
        description: Install Sysinternals
        allowPrerelease: false
      settings:
        id: Microsoft.Sysinternals
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powerToysPackage
      directives:
        description: Install PowerToys
        allowPrerelease: false
      settings:
        id: Microsoft.PowerToys
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: sQLiteStudioPackage
      directives:
        description: Install SQLiteStudio
        allowPrerelease: false
      settings:
        id: PawelSalawa.SQLiteStudio
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: devTunnelsPackage
      directives:
        description: Install Microsoft DevTunnels
        allowPrerelease: false
      settings:
        id: Microsoft.devtunnel
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: devProxyPackage
      directives:
        description: Install Microsoft DevProxy
        allowPrerelease: false
      settings:
        id: Microsoft.DevProxy
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: jetbrainsRiderPackage
      directives:
        description: Install JetBrains Rider
        allowPrerelease: false
      settings:
        id: JetBrains.Rider
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: firefoxPackage
      directives:
        description: Install Firefox Developer Edition
        allowPrerelease: false
      settings:
        id: Mozilla.Firefox.DeveloperEdition
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: firefoxDeveloperPackage
      directives:
        description: Install Firefox Developer
        allowPrerelease: false
      settings:
        id: Mozilla.Firefox
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: edgeDevPackage
      directives:
        description: Install Edge Dev
        allowPrerelease: false
      settings:
        id: Microsoft.Edge.Dev
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: windowsTerminalPackage
      directives:
        description: Install Microsoft Windows Terminal
        allowPrerelease: false
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: discordPackage
      directives:
        description: Install Discord
        allowPrerelease: false
      settings:
        id: Discord.Discord
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: slackPackage
      directives:
        description: Install Slack
        allowPrerelease: false
      settings:
        id: SlackTechnologies.Slack
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nordPassPackage
      directives:
        description: Install Nordpass
        allowPrerelease: false
      settings:
        id: NordSecurity.NordPass
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: lmStudioPackage
      directives:
        description: Install LM Studio
        allowPrerelease: false
      settings:
        id: ElementLabs.LMStudio
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: spotifyPackage
      directives:
        description: Install Spotify
        allowPrerelease: false
      settings:
        id: Spotify.Spotify
        source: winget

  configurationVersion: 0.2.0